- dynamic_vino_lib/include/dynamic_vino_lib/outputs/base_output.hpp
- dynamic_vino_lib/src/pipeline.cpp
> fix launching bug.

- README.md
- dynamic_vino_lib/CMakeLists.txt
- sample/CMakeLists.txt
- sample/param/pipeline_object_oss.yaml
- sample/param/pipeline_people_oss.yaml
- sample/pipeline_with_params.cpp
Add support for OpenVINO open source code
> Open source

- dynamic_vino_lib/src/pipeline_manager.cpp
- sample/param/pipeline_object.yaml
- sample/param/pipeline_object_oss.yaml
@LewisLiuPub @chaoli2  Modified object.yaml and add name check in pipeline-manager, please review.
> Object detection works now

- dynamic_vino_lib/include/dynamic_vino_lib/inputs/base_input.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/pipeline.hpp
- dynamic_vino_lib/src/inputs/image_input.cpp
- dynamic_vino_lib/src/inputs/realsense_camera.cpp
- dynamic_vino_lib/src/inputs/realsense_camera_topic.cpp
- dynamic_vino_lib/src/inputs/standard_camera.cpp
- dynamic_vino_lib/src/inputs/video_input.cpp
- dynamic_vino_lib/src/outputs/ros_topic_output.cpp
- dynamic_vino_lib/src/outputs/rviz_output.cpp
- dynamic_vino_lib/src/pipeline_manager.cpp
@LewisLiuPub @chaoli2 This PR fixes the frame_id issue in #33. Please review
> Update frame_id for different inputs

- README.md
- doc/BINARY_VERSION_README.md
- sample/launch/pipeline_object_oss_topic.launch.py
- sample/launch/pipeline_object_topic.launch.py
- sample/param/pipeline_object_oss_topic.yaml
- sample/param/pipeline_object_topic.yaml
@LewisLiuPub This PR provides updates for
-  add object detection launch file to support connect oa
-  modify subscribed topic
> Support oa

- doc/BINARY_VERSION_README.md
- doc/OPEN_SOURCE_CODE_README.md
- script/environment_setup.sh
- script/environment_setup_binary.sh
@LewisLiuPub @chaoli2 @houk-intel  This PR provides updates for
- modify readme and script to support R5
> modify readme and script to support R5

- README.md
@LewisLiuPub This PR provides updates for
- Enable NCS under the OpenVINO Open Source version
> Enable NCS under the OpenVINO Open Source version

- dynamic_vino_lib/include/dynamic_vino_lib/inputs/base_input.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/inputs/realsense_camera_topic.hpp
- dynamic_vino_lib/src/inputs/image_input.cpp
- dynamic_vino_lib/src/inputs/realsense_camera.cpp
- dynamic_vino_lib/src/inputs/realsense_camera_topic.cpp
- dynamic_vino_lib/src/inputs/standard_camera.cpp
- dynamic_vino_lib/src/inputs/video_input.cpp
- dynamic_vino_lib/src/outputs/ros_topic_output.cpp
- dynamic_vino_lib/src/outputs/rviz_output.cpp
@LewisLiuPub This pull request accept header construction from RealsenseCameraTopic and other inputs. Please review.
> Support constructing header from input

- doc/BINARY_VERSION_README.md
- doc/OPEN_SOURCE_CODE_README.md
- dynamic_vino_lib/CMakeLists.txt
- dynamic_vino_lib/include/dynamic_vino_lib/inputs/base_input.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/inputs/realsense_camera_topic.hpp
- dynamic_vino_lib/package.xml
- dynamic_vino_lib/src/models/base_model.cpp
- sample/CMakeLists.txt
- sample/launch/pipeline_reidentification.launch.py
- sample/launch/pipeline_reidentification_oss.launch.py
- sample/package.xml
- script/environment_setup.sh
- script/environment_setup_binary.sh
- script/modules.conf
@LewisLiuPub This PR provides updates for
- Enable librealsensev2.17.1
> Enable libreansensev2.17.1

- README.md
- doc/BINARY_VERSION_README.md
- sample/param/pipeline_object.yaml
- sample/param/pipeline_object_oss.yaml
- sample/param/pipeline_object_oss_topic.yaml
- sample/param/pipeline_object_topic.yaml
@LewisLiuPub This PR provides updates for
- support object detection with NCS/NCS2
> Support fp16

- dynamic_vino_lib/src/pipeline.cpp
@chaoli2  This PR fixed the problem of fps.
> fix wrong fps issue

- dynamic_vino_lib/include/dynamic_vino_lib/inputs/base_input.hpp
- sample/src/image_object_client.cpp
This pull request fix issue #78, which is caused by using legacy script and incorrect function call.
> Fix compile error issues of

- doc/BINARY_VERSION_README.md
- doc/OPEN_SOURCE_CODE_README.md
- script/environment_setup.sh
- script/environment_setup_binary.sh
- script/modules.conf
@LewisLiuPub  please have a review.
> Add warning

- dynamic_vino_lib/src/inputs/realsense_camera_topic.cpp
- dynamic_vino_lib/src/outputs/ros_topic_output.cpp
- dynamic_vino_lib/src/outputs/rviz_output.cpp
> update create_subscription invocation due to dashing's changes.

- doc/BINARY_VERSION_README.md
- doc/OPEN_SOURCE_CODE_README.md
- script/environment_setup.sh
- script/environment_setup_binary.sh
@LewisLiuPub  
This PR upgrades librealsense to v2.23.0. Please have a review.
> upgrade librealsense to 2.23.0

- dynamic_vino_lib/include/dynamic_vino_lib/pipeline.hpp
- dynamic_vino_lib/src/pipeline.cpp
change static variable to class variable
> fix multi-pipeline fps display issue

- sample/CMakeLists.txt
> remove dependency to lib rviz_yaml_cpp_vedor

- sample/launch/pipeline_object_topic.launch.py
- sample/launch/pipeline_object_yolo_topic.launch.py
- sample/launch/pipeline_segmentation.launch.py
> removing realsense_node auto-launching by OpenVINO component.

- sample/launch/pipeline_object.launch.py
- sample/param/pipeline_object.yaml
> revert the configuration for pipeline_object.

- .gitignore
- dynamic_vino_lib/CMakeLists.txt
- dynamic_vino_lib/include/dynamic_vino_lib/engines/engine.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/inferences/object_segmentation.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/object_segmentation_model.hpp
- dynamic_vino_lib/src/engines/engine.cpp
- dynamic_vino_lib/src/factory.cpp
- dynamic_vino_lib/src/inferences/object_segmentation.cpp
- dynamic_vino_lib/src/models/object_segmentation_model.cpp
- dynamic_vino_lib/src/pipeline_manager.cpp
@chaoli2 , please have a review, since you are aldready working on the segmentation features.
> Fix segmentation

- CMakeLists.txt
- config/object_detection_default.yaml
- include/openvino/object_detection_ssd.hpp
- include/openvino/object_detection_yolov2.hpp
- include/openvino/object_segmentation.hpp
- include/openvino/openvino_base.hpp
- include/openvino/openvino_factory.hpp
- include/openvino/reidentification.hpp
- include/openvino/tracker.hpp
- package.xml
- src/object_detection_ssd.cpp
- src/object_detection_yolov2.cpp
- src/object_segmentation.cpp
- src/openvino_base.cpp
- src/openvino_factory.cpp
- src/reidentification.cpp
- src/tracker.cpp
Signed-off-by: Xiaojun <xiaojun.huang@intel.com>
> initial commit of openvino for robot devkit

- CMakeLists.txt
- include/openvino/openvino_factory.hpp
- package.xml
- src/openvino_factory.cpp
Signed-off-by: Xiaojun <xiaojun.huang@intel.com>
> make openvino node as a component

- config/object_detection.yaml
- src/object_segmentation.cpp
- src/openvino_base.cpp
> update the method of reading label file

- README.md
> Update README for robot_devkit

- dynamic_vino_lib/CMakeLists.txt
- dynamic_vino_lib/include/dynamic_vino_lib/engines/engine.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/engines/engine_manager.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/base_model.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/pipeline_manager.hpp
- dynamic_vino_lib/src/engines/engine.cpp
- dynamic_vino_lib/src/engines/engine_manager.cpp
- dynamic_vino_lib/src/factory.cpp
- dynamic_vino_lib/src/pipeline_manager.cpp
- sample/param/pipeline_segmentation.yaml
refactoring code to support both old InferencePlugins(before OpenVINO Version 2019R2) and new Inference Core(2019R2 and newer version).
> Support multiple engines

- README.md
- doc/BINARY_VERSION_README.md
- doc/OPEN_SOURCE_CODE_README.md
- sample/param/image_people_server.yaml
- sample/param/pipeline_face_reidentification.yaml
- sample/param/pipeline_image.yaml
- sample/param/pipeline_image_video.yaml
- sample/param/pipeline_people.yaml
- sample/param/pipeline_people_ip.yaml
- sample/param/pipeline_reidentification.yaml
- sample/param/pipeline_segmentation.yaml
- sample/param/pipeline_vehicle_detection.yaml
- script/environment_setup.sh
- script/environment_setup_binary.sh
@LewisLiuPub 
This PR update yaml, script and readme to support OpenVINO R3.Please have a review.
> Support r3

- doc/OBJECT_DETECTION.md
> update Readme for Object Detection.

- dynamic_vino_lib/src/outputs/image_window_output.cpp
fix the issue: https://github.com/intel/ros2_openvino_toolkit/issues/132
> include iomanip header for std::setprecision

- openvino_ros/CMakeLists.txt
- openvino_ros/include/openvino/object_detection_ssd.hpp
- openvino_ros/include/openvino/object_detection_yolov2.hpp
- openvino_ros/include/openvino/object_segmentation.hpp
- openvino_ros/include/openvino/openvino_base.hpp
- openvino_ros/include/openvino/reidentification.hpp
- openvino_ros/package.xml
- openvino_ros/src/object_detection_ssd.cpp
- openvino_ros/src/object_detection_yolov2.cpp
- openvino_ros/src/object_segmentation.cpp
- openvino_ros/src/openvino_base.cpp
- openvino_ros/src/openvino_factory.cpp
- openvino_ros/src/reidentification.cpp
we can use opencv4.1 in openvino toolkit now.
Signed-off-by: Xiaojun <xiaojun.huang@intel.com>
> [robot_devkit]some changes for performance optimization

- openvino_ros/CMakeLists.txt
- openvino_ros/src/openvino_base.cpp
> add CPU plugin support

- openvino_node/config/object_detection.yaml
- openvino_ros/include/openvino/openvino_base.hpp
- openvino_ros/src/openvino_base.cpp
Signed-off-by: Xiaojun <xiaojun.huang@intel.com>
> [robot_devkit] support new API of InferenceEngine::Core

- openvino_ros/CMakeLists.txt
- openvino_ros/include/openvino/object_detection_yolov2.hpp
- openvino_ros/src/object_detection_yolov2.cpp
- openvino_ros/src/openvino_factory.cpp
> [robot_devkit] refactor YOLOv2 module for parallel acceleration

- openvino_ros/CMakeLists.txt
- openvino_ros/include/openvino/object_segmentation.hpp
- openvino_ros/src/object_segmentation.cpp
- openvino_ros/src/openvino_factory.cpp
> [robot_devkit] refactor object segmentation for parallel acceleration

- openvino_ros/CMakeLists.txt
- openvino_ros/include/openvino/reidentification.hpp
- openvino_ros/src/openvino_factory.cpp
- openvino_ros/src/reidentification.cpp
> [robot_devkit] refactor reid module for parallel acceleration

- openvino_node/config/face_detection.yaml
- openvino_node/config/face_reidentification.yaml
- openvino_node/config/object_detection.yaml
- openvino_node/config/object_segmentation.yaml
- openvino_node/config/person_detection.yaml
- openvino_node/config/person_reidentification.yaml
- openvino_node/launch/rs_face_reid.launch.py
- openvino_node/launch/rs_osg.launch.py
- openvino_node/launch/rs_person_reid.launch.py
> [robot_devkit]  add config and launch files in openvino_node

- openvino_ros/CMakeLists.txt
- openvino_ros/include/openvino/object_detection_ssd.hpp
- openvino_ros/include/openvino/object_detection_yolov2.hpp
- openvino_ros/include/openvino/object_segmentation.hpp
- openvino_ros/include/openvino/openvino_base.hpp
- openvino_ros/include/openvino/reidentification.hpp
- openvino_ros/package.xml
- openvino_ros/src/object_detection_ssd.cpp
- openvino_ros/src/object_detection_yolov2.cpp
- openvino_ros/src/object_segmentation.cpp
- openvino_ros/src/openvino_base.cpp
- openvino_ros/src/reidentification.cpp
- openvino_utils/include/visualization.hpp
> [robot_devkit] replace rdk_interface with ros2_object_msgs

- openvino_ros/CMakeLists.txt
> [robot_devkit] set cpu plugin path in CMakeLists.txt

- openvino_ros/src/reidentification.cpp
> [robot_devkit] fix crash issue for Re-ID features

- dynamic_vino_lib/include/dynamic_vino_lib/inputs/image_topic.hpp
- dynamic_vino_lib/src/inputs/image_topic.cpp
> revert uniqueptr for image topic handling.

- openvino_node/config/face_detection.yaml
- openvino_node/config/face_reidentification.yaml
- openvino_node/config/object_detection.yaml
- openvino_node/config/object_segmentation.yaml
- openvino_node/config/person_detection.yaml
- openvino_node/config/person_reidentification.yaml
- openvino_node/launch/object_detection.launch.py
- openvino_node/launch/rs_face_reid.launch.py
- openvino_node/launch/rs_od.launch.py
- openvino_node/launch/rs_osg.launch.py
- openvino_node/launch/rs_person_reid.launch.py
- openvino_ros/src/object_detection_ssd.cpp
- openvino_ros/src/object_detection_yolov2.cpp
- openvino_ros/src/object_segmentation.cpp
- openvino_ros/src/reidentification.cpp
> [robot_devkit]: add remapping rules for each model

- script/environment_setup.sh
- script/environment_setup_binary.sh
> fix install issues

- tests/CMakeLists.txt
@LewisLiuPub 
This PR fixed the build issue.
> fix the build issue

- openvino_node/launch/rs_od.launch.py
- openvino_node/launch/rviz/default.rviz
- openvino_utils/include/openvino/viz_detection.hpp
- openvino_utils/src/viz_detection.cpp
> [robot_devkit]: support detection results display in Rviz

- doc/installation/installation.md
- tests/src/lib/unittest_createPipelineCheck.cpp
- tests/src/service/unittest_objectService.cpp
- tests/src/service/unittest_peopleService.cpp
@LewisLiuPub 
This PR fixed the readme issue and test case issue.Please have a review.Thanks.
> fix readme and test case issue

- dynamic_vino_lib/src/inputs/image_topic.cpp
Replace fixed subscribtion topic from /camera/color/image_raw to /openvino_toolkit/image_raw, aligned with tutorial and enable remappings in launch script.
> Fix remappings issue for launch script

- dynamic_vino_lib/include/dynamic_vino_lib/models/age_gender_detection_model.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/attributes/base_attribute.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/base_model.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/emotion_detection_model.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/head_pose_detection_model.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/license_plate_detection_model.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/object_detection_ssd_model.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/object_detection_yolov2_model.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/object_segmentation_model.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/person_attribs_detection_model.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/person_reidentification_model.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/models/vehicle_attribs_detection_model.hpp
- dynamic_vino_lib/include/dynamic_vino_lib/utils/version_info.hpp
- dynamic_vino_lib/src/engines/engine_manager.cpp
- dynamic_vino_lib/src/models/age_gender_detection_model.cpp
- dynamic_vino_lib/src/models/attributes/ssd_model_attr.cpp
- dynamic_vino_lib/src/models/base_model.cpp
- dynamic_vino_lib/src/models/emotion_detection_model.cpp
- dynamic_vino_lib/src/models/face_reidentification_model.cpp
- dynamic_vino_lib/src/models/head_pose_detection_model.cpp
- dynamic_vino_lib/src/models/landmarks_detection_model.cpp
- dynamic_vino_lib/src/models/license_plate_detection_model.cpp
- dynamic_vino_lib/src/models/object_detection_ssd_model.cpp
- dynamic_vino_lib/src/models/object_detection_yolov2_model.cpp
- dynamic_vino_lib/src/models/object_segmentation_model.cpp
- dynamic_vino_lib/src/models/person_attribs_detection_model.cpp
- dynamic_vino_lib/src/models/person_reidentification_model.cpp
- dynamic_vino_lib/src/models/vehicle_attribs_detection_model.cpp
Changes to support new Inference Engine APIs in 2021.3.Changes to support new Inference Engine APIs in 2021.3.
> build on OpenVINO 2021.3 release

- .ci_local_test/Jenkinsfile
signed-off-by: huangjiafengx <jiafengx.huang@intel.com>
> Get ready the jenkinsfile for ROS2_OpenVino self-host automation test

- doc/quick_start/getting_started_with_Galactic_Ubuntu20.04.md
- sample/param/pipeline_image.yaml
- sample/src/pipeline_composite.cpp
Signed-off-by: Liu, Wei Zhi <wei.zhi.liu@intel.com>
> update document to support Galactic and latest OpenVINO 2021.4.

- .ci_local_test/README.md
> The Jenkinsfile Introductions

- .ci_local_test/Jenkinsfile
- .ci_local_test/README.md
> Adding the jenkinsfile for galactic branch

- .ci_local_test/Jenkinsfile
> Updating the Jenkinsfile for PR test

- .ci_local_test/Jenkinsfile
> Enable environment information for email.

- .ci_local_test/Jenkinsfile
- .ci_local_test/README.md
> Adding Jenkins file to foxy branch for ros2_openvino_toolkit

- .ci_local_test/Jenkinsfile
> Updating the Jenkinsfile

- .ci_local_test/Jenkinsfile
- .ci_local_test/README.md
> Adding Jenkins CI test to dashing branch for ros2_openvino_toolkit

- data/labels/object_detection/vehicle-license-plate-detection-barrier-0106.labels
- dynamic_vino_lib/include/dynamic_vino_lib/models/vehicle_attribs_detection_model.hpp
- dynamic_vino_lib/src/inferences/license_plate_detection.cpp
Signed-off-by: Fan, Tao <tao.fan@intel.com>
> fix vehicle attribs and license plate

- doc/quick_start/tutorial_for_yolov7_converted.md
- openvino_wrapper_lib/CMakeLists.txt
- openvino_wrapper_lib/include/openvino_wrapper_lib/models/base_model.hpp
- openvino_wrapper_lib/include/openvino_wrapper_lib/models/object_detection_yolov7_model.hpp
- openvino_wrapper_lib/include/openvino_wrapper_lib/pipeline_params.hpp
- openvino_wrapper_lib/src/models/object_detection_yolov5_model.cpp
- openvino_wrapper_lib/src/models/object_detection_yolov7_model.cpp
- openvino_wrapper_lib/src/pipeline_manager.cpp
- sample/param/pipeline_object_yolo.yaml
Add support for YOLO v7
Add new class for YOLO v7 model
Modify PipelineManager to run either v5 or v7 model 
Add documentation to explain YOLO v7 model conversion
Fixes #255
---------
Signed-off-by: Taylor Courier <taylor.courier@intel.com>
Signed-off-by: Andrew Capatina <andrew.capatina@intel.com>
Co-authored-by: capp21 <andrew.capatina@intel.com>
Co-authored-by: Ibrahim Ali <ibrahim.ali@intel.com>
> [Issue: #255] Add YOLO v7 support

- openvino_wrapper_lib/include/openvino_wrapper_lib/models/base_model.hpp
- openvino_wrapper_lib/include/openvino_wrapper_lib/models/object_detection_yolov5_model.hpp
- openvino_wrapper_lib/src/models/base_model.cpp
- openvino_wrapper_lib/src/models/object_detection_ssd_model.cpp
- openvino_wrapper_lib/src/models/object_detection_yolov5_model.cpp
Refine matToBlob function from derived classes to BaseModel.
> Refine matToBlob function from derived classes to BaseModel

- README.md
- doc/quick_start/Deploy_under_windows.md
- doc/quick_start/getting_started_with_Dashing_Ubuntu18.04.md
- doc/quick_start/getting_started_with_ros2_ov2.0.md
- docker/docker_instructions_ov2.0.md
- docker/ros2_2021.4/ros2_dashing/docker_instraction.md
- docker/ros2_2021.4/ros2_foxy/docker_instraction.md
- docker/ros2_2021.4/ros2_galactic/docker_instructions.md
Add document for windows deployment.
ros2_object_msgs compiled pass.
WIP due to ros2 humble lack of package dependencies on windows.
Update documents, fix typos and refine format for ros2.
> Add document for windows deployment and update documents

- openvino_wrapper_lib/src/models/object_segmentation_instance_model.cpp
> fix-bug: ROI (width/height) error when NMS-threshold is set to high
